/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 33
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 28
#define ALIAS_COUNT 2
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_EQ = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_STAR = 5,
  anon_sym_QMARK = 6,
  anon_sym_SQUOTE = 7,
  sym_generic_token = 8,
  sym_literal_token = 9,
  anon_sym_COLON = 10,
  anon_sym_PIPE = 11,
  sym_token_identifier = 12,
  sym_comment = 13,
  sym_grammar = 14,
  sym_node = 15,
  sym_rule = 16,
  sym__atom_rule = 17,
  sym_repetition = 18,
  sym_optional = 19,
  sym_node_rule = 20,
  sym_token = 21,
  sym_label = 22,
  sym_sequence = 23,
  sym_alternation = 24,
  aux_sym_grammar_repeat1 = 25,
  aux_sym_sequence_repeat1 = 26,
  aux_sym_alternation_repeat1 = 27,
  alias_sym_definition = 28,
  alias_sym_label_name = 29,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_EQ] = "=",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_STAR] = "*",
  [anon_sym_QMARK] = "\?",
  [anon_sym_SQUOTE] = "'",
  [sym_generic_token] = "generic_token",
  [sym_literal_token] = "literal_token",
  [anon_sym_COLON] = ":",
  [anon_sym_PIPE] = "|",
  [sym_token_identifier] = "token_identifier",
  [sym_comment] = "comment",
  [sym_grammar] = "grammar",
  [sym_node] = "node",
  [sym_rule] = "rule",
  [sym__atom_rule] = "_atom_rule",
  [sym_repetition] = "repetition",
  [sym_optional] = "optional",
  [sym_node_rule] = "node_rule",
  [sym_token] = "token",
  [sym_label] = "label",
  [sym_sequence] = "sequence",
  [sym_alternation] = "alternation",
  [aux_sym_grammar_repeat1] = "grammar_repeat1",
  [aux_sym_sequence_repeat1] = "sequence_repeat1",
  [aux_sym_alternation_repeat1] = "alternation_repeat1",
  [alias_sym_definition] = "definition",
  [alias_sym_label_name] = "label_name",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [sym_generic_token] = sym_generic_token,
  [sym_literal_token] = sym_literal_token,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_token_identifier] = sym_token_identifier,
  [sym_comment] = sym_comment,
  [sym_grammar] = sym_grammar,
  [sym_node] = sym_node,
  [sym_rule] = sym_rule,
  [sym__atom_rule] = sym__atom_rule,
  [sym_repetition] = sym_repetition,
  [sym_optional] = sym_optional,
  [sym_node_rule] = sym_node_rule,
  [sym_token] = sym_token,
  [sym_label] = sym_label,
  [sym_sequence] = sym_sequence,
  [sym_alternation] = sym_alternation,
  [aux_sym_grammar_repeat1] = aux_sym_grammar_repeat1,
  [aux_sym_sequence_repeat1] = aux_sym_sequence_repeat1,
  [aux_sym_alternation_repeat1] = aux_sym_alternation_repeat1,
  [alias_sym_definition] = alias_sym_definition,
  [alias_sym_label_name] = alias_sym_label_name,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_generic_token] = {
    .visible = true,
    .named = true,
  },
  [sym_literal_token] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_token_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_grammar] = {
    .visible = true,
    .named = true,
  },
  [sym_node] = {
    .visible = true,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym__atom_rule] = {
    .visible = false,
    .named = true,
  },
  [sym_repetition] = {
    .visible = true,
    .named = true,
  },
  [sym_optional] = {
    .visible = true,
    .named = true,
  },
  [sym_node_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_token] = {
    .visible = true,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_alternation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_grammar_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sequence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_alternation_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_definition] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_label_name] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_definition,
  },
  [2] = {
    [0] = alias_sym_label_name,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 5,
  [7] = 7,
  [8] = 7,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 22,
  [25] = 20,
  [26] = 18,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '\'', 16,
        '(', 11,
        ')', 12,
        '*', 13,
        '/', 4,
        ':', 19,
        '=', 10,
        '?', 14,
        '|', 20,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 1:
      if (lookahead == '\'') ADVANCE(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(15);
      if (lookahead == '/') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(27);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == '\\') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(25);
      END_STATE();
    case 6:
      if (lookahead == '\'' ||
          lookahead == '\\') ADVANCE(25);
      END_STATE();
    case 7:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(1);
      END_STATE();
    case 8:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(2);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      if (lookahead == '#') ADVANCE(7);
      if (lookahead == '@') ADVANCE(8);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_generic_token);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_literal_token);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_token_identifier);
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '\'') ADVANCE(27);
      if (lookahead == '\\') ADVANCE(26);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_token_identifier);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == '\\') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(25);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_token_identifier);
      if (lookahead == '/') ADVANCE(22);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_token_identifier);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\'' ||
          lookahead == '\\') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 5},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_generic_token] = ACTIONS(1),
    [sym_literal_token] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_grammar] = STATE(30),
    [sym_node] = STATE(19),
    [aux_sym_grammar_repeat1] = STATE(19),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_rule] = STATE(27),
    [sym__atom_rule] = STATE(11),
    [sym_repetition] = STATE(11),
    [sym_optional] = STATE(11),
    [sym_node_rule] = STATE(11),
    [sym_token] = STATE(11),
    [sym_label] = STATE(11),
    [sym_sequence] = STATE(18),
    [sym_alternation] = STATE(23),
    [aux_sym_sequence_repeat1] = STATE(6),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [sym_generic_token] = ACTIONS(15),
    [sym_literal_token] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym_rule] = STATE(29),
    [sym__atom_rule] = STATE(11),
    [sym_repetition] = STATE(11),
    [sym_optional] = STATE(11),
    [sym_node_rule] = STATE(11),
    [sym_token] = STATE(11),
    [sym_label] = STATE(11),
    [sym_sequence] = STATE(26),
    [sym_alternation] = STATE(23),
    [aux_sym_sequence_repeat1] = STATE(5),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [sym_generic_token] = ACTIONS(15),
    [sym_literal_token] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym__atom_rule] = STATE(11),
    [sym_repetition] = STATE(11),
    [sym_optional] = STATE(11),
    [sym_node_rule] = STATE(11),
    [sym_token] = STATE(11),
    [sym_label] = STATE(11),
    [aux_sym_sequence_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(22),
    [anon_sym_RPAREN] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(25),
    [sym_generic_token] = ACTIONS(28),
    [sym_literal_token] = ACTIONS(28),
    [anon_sym_PIPE] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym__atom_rule] = STATE(11),
    [sym_repetition] = STATE(11),
    [sym_optional] = STATE(11),
    [sym_node_rule] = STATE(11),
    [sym_token] = STATE(11),
    [sym_label] = STATE(11),
    [aux_sym_sequence_repeat1] = STATE(4),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(31),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [sym_generic_token] = ACTIONS(15),
    [sym_literal_token] = ACTIONS(15),
    [anon_sym_PIPE] = ACTIONS(31),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym__atom_rule] = STATE(11),
    [sym_repetition] = STATE(11),
    [sym_optional] = STATE(11),
    [sym_node_rule] = STATE(11),
    [sym_token] = STATE(11),
    [sym_label] = STATE(11),
    [aux_sym_sequence_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(31),
    [sym_identifier] = ACTIONS(33),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [sym_generic_token] = ACTIONS(15),
    [sym_literal_token] = ACTIONS(15),
    [anon_sym_PIPE] = ACTIONS(31),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    STATE(6), 1,
      aux_sym_sequence_repeat1,
    STATE(21), 1,
      sym_sequence,
    ACTIONS(15), 2,
      sym_generic_token,
      sym_literal_token,
    STATE(11), 6,
      sym__atom_rule,
      sym_repetition,
      sym_optional,
      sym_node_rule,
      sym_token,
      sym_label,
  [31] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    STATE(5), 1,
      aux_sym_sequence_repeat1,
    STATE(21), 1,
      sym_sequence,
    ACTIONS(15), 2,
      sym_generic_token,
      sym_literal_token,
    STATE(11), 6,
      sym__atom_rule,
      sym_repetition,
      sym_optional,
      sym_node_rule,
      sym_token,
      sym_label,
  [62] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(36), 2,
      sym_generic_token,
      sym_literal_token,
    STATE(14), 6,
      sym__atom_rule,
      sym_repetition,
      sym_optional,
      sym_node_rule,
      sym_token,
      sym_label,
  [87] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(40), 1,
      anon_sym_SQUOTE,
    ACTIONS(42), 1,
      anon_sym_COLON,
    ACTIONS(38), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_QMARK,
      sym_generic_token,
      sym_literal_token,
      anon_sym_PIPE,
      sym_identifier,
  [108] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      anon_sym_STAR,
    ACTIONS(48), 1,
      anon_sym_QMARK,
    ACTIONS(50), 1,
      anon_sym_SQUOTE,
    ACTIONS(44), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_generic_token,
      sym_literal_token,
      anon_sym_PIPE,
      sym_identifier,
  [130] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 1,
      anon_sym_SQUOTE,
    ACTIONS(52), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_QMARK,
      sym_generic_token,
      sym_literal_token,
      anon_sym_PIPE,
      sym_identifier,
  [148] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      anon_sym_SQUOTE,
    ACTIONS(56), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_QMARK,
      sym_generic_token,
      sym_literal_token,
      anon_sym_PIPE,
      sym_identifier,
  [166] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_SQUOTE,
    ACTIONS(60), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_QMARK,
      sym_generic_token,
      sym_literal_token,
      anon_sym_PIPE,
      sym_identifier,
  [184] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_SQUOTE,
    ACTIONS(64), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_QMARK,
      sym_generic_token,
      sym_literal_token,
      anon_sym_PIPE,
      sym_identifier,
  [202] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_SQUOTE,
    ACTIONS(68), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_QMARK,
      sym_generic_token,
      sym_literal_token,
      anon_sym_PIPE,
      sym_identifier,
  [220] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      ts_builtin_sym_end,
    ACTIONS(74), 1,
      sym_identifier,
    STATE(17), 2,
      sym_node,
      aux_sym_grammar_repeat1,
  [234] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_PIPE,
    STATE(20), 1,
      aux_sym_alternation_repeat1,
    ACTIONS(77), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [248] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(81), 1,
      ts_builtin_sym_end,
    STATE(17), 2,
      sym_node,
      aux_sym_grammar_repeat1,
  [262] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_PIPE,
    STATE(22), 1,
      aux_sym_alternation_repeat1,
    ACTIONS(83), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [276] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 4,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      sym_identifier,
  [286] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_PIPE,
    STATE(22), 1,
      aux_sym_alternation_repeat1,
    ACTIONS(85), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [300] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      sym_identifier,
  [309] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_RPAREN,
    ACTIONS(92), 1,
      anon_sym_PIPE,
    STATE(24), 1,
      aux_sym_alternation_repeat1,
  [322] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_RPAREN,
    ACTIONS(95), 1,
      anon_sym_PIPE,
    STATE(24), 1,
      aux_sym_alternation_repeat1,
  [335] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_RPAREN,
    ACTIONS(95), 1,
      anon_sym_PIPE,
    STATE(25), 1,
      aux_sym_alternation_repeat1,
  [348] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [356] = 2,
    ACTIONS(99), 1,
      sym_token_identifier,
    ACTIONS(101), 1,
      sym_comment,
  [363] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      anon_sym_RPAREN,
  [370] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      ts_builtin_sym_end,
  [377] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_SQUOTE,
  [384] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 31,
  [SMALL_STATE(9)] = 62,
  [SMALL_STATE(10)] = 87,
  [SMALL_STATE(11)] = 108,
  [SMALL_STATE(12)] = 130,
  [SMALL_STATE(13)] = 148,
  [SMALL_STATE(14)] = 166,
  [SMALL_STATE(15)] = 184,
  [SMALL_STATE(16)] = 202,
  [SMALL_STATE(17)] = 220,
  [SMALL_STATE(18)] = 234,
  [SMALL_STATE(19)] = 248,
  [SMALL_STATE(20)] = 262,
  [SMALL_STATE(21)] = 276,
  [SMALL_STATE(22)] = 286,
  [SMALL_STATE(23)] = 300,
  [SMALL_STATE(24)] = 309,
  [SMALL_STATE(25)] = 322,
  [SMALL_STATE(26)] = 335,
  [SMALL_STATE(27)] = 348,
  [SMALL_STATE(28)] = 356,
  [SMALL_STATE(29)] = 363,
  [SMALL_STATE(30)] = 370,
  [SMALL_STATE(31)] = 377,
  [SMALL_STATE(32)] = 384,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grammar, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence, 1, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_sequence, 1, 0, 0), SHIFT(10),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_rule, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node_rule, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_sequence_repeat1, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_repetition, 2, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_repetition, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optional, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_optional, 2, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 3, 0, 2),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_label, 3, 0, 2),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_token, 3, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_token, 3, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__atom_rule, 3, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__atom_rule, 3, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_grammar_repeat1, 2, 0, 0),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_grammar_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alternation, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grammar, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alternation, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_alternation_repeat1, 2, 0, 0),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_alternation_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 1, 0, 0),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_alternation_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 3, 0, 1),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [105] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ungrammar(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
